name: build and publish a release

on:
  release:
    types: [published]

env:
  BINTRAY_USER: ${{ secrets.bintray_user }}
  BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
  BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}

jobs:
  build-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.265'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Windows
        if: matrix.os == 'windows-latest'
        run: |
          rm.exe "C:/WINDOWS/system32/bash.EXE"
          echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          choco install llvm
          echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # https://youtrack.jetbrains.com/issue/KT-42485
          echo "LIBCLANG_DISABLE_CRASH_RECOVERY=1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Setup kodein.local.properties
        run: cp .github/conf/kodein.local.${{ matrix.os }}.properties kodein.local.properties
      - name: Set up Gradle & Konan
        shell: bash
        run: ./gradlew
      - name: Check
        shell: bash
        run: ./gradlew check
      - name: Upload
        shell: bash
        run: ./gradlew hostOnlyPublish --stacktrace
      - name: Discard
        if: ${{ failure() || cancelled() }}
        shell: bash
        run: ./gradlew postBintrayDiscard

  build-upload-publish:
    needs: build-upload
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.265'
      - name: Setup Android SDK dir
        run: echo sdk.dir=$ANDROID_HOME > local.properties
      - name: install default NDK for AGP
        run: $ANDROID_HOME/tools/bin/sdkmanager "ndk;21.0.6113669"
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup kodein.local.properties
        run: cp .github/conf/kodein.local.macos-latest.properties kodein.local.properties
      - name: Set up Gradle & Konan
        shell: bash
        run: ./gradlew
      - name: Check
        shell: bash
        run: ./gradlew check
      - name: Check Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          ndk: 21.3.6528147
          cmake: 3.10.2.4988404
          script: ./gradlew connectedCheck
      - name: Upload
        shell: bash
        run: ./gradlew publish --stacktrace
      - name: Discard
        if: ${{ failure() || cancelled() }}
        shell: bash
        run: ./gradlew postBintrayDiscard
      - name: Publish
        shell: bash
        run: ./gradlew postBintrayPublish
